### ISSUE TITLE
Got error "Date outside of valid range" when selected maxDate

### ISSUE THREAD

**Issue by julie2013** [bendavis78/paper-date-picker#139]
I set a maxDate in paper-date-picker,  for example: 
`<paper-date-picker id="picker" max-date="October 10, 2016" locale="en"></paper-date-picker>`

But when select "October 10, 2016" from calendar, the window will get back to previous month automatically,  and the Chrome console output this error: "Date outside of valid range: Mon Oct 10 2016 13:35:17 GMT-0700 (PDT)".

Did I do something wrong? Is maxDate excluded?  How can I change the max Date colour to grey in calendar if it can not be selected?

**Comment by Ixl123** [comment]
I have the same issue setting the max date property is not working for me as well.

**Comment by Ixl123** [comment]
The problem is in this function

```
_withinValidRange: function(date) {
        if (this._isValidDate(date)) {
          return (!this.minDate || date >= this.minDate) && (!this.maxDate || date <= this.maxDate);
       }
        return false;
 },
```
min and maxDate have no time value but the date which we have set has a time value so if you dont provide a time value for example 23:59 this statement is going to return false when you select the same date as the maxDate.

workarounds for now:

you can specify a time for the max-date value:

<paper-date-picker id="picker" max-date="October 10, 2016, 23:59" locale="en"></paper-date-picker>
