### ISSUE TITLE
Cannot set property isTouch of #<paper-date-picker> which has only a getter

### ISSUE THREAD

**Issue by k3karthic** [bendavis78/paper-date-picker#164]
The property isTouch is defined as readOnly on 'paper-date-picker', but the property is set during the ready callback. This error only seems to occur when i bundle my polymer project. Hasn't show up during regular development.

As a hack to get my production site up I changed the readOnly value to false but i'm not sure what the right approach is to fix this.

**Comment by admwx7** [comment]
When using readOnly instead of setting via `this.set('isTouch', true)` or `this.isTouch = true;` you have to use the setter provided for internal use only: `this._setIsTouch(true)` I checked the code associated with `isTouch` in master and it looks like we're properly setting everywhere it's used, so if this is still an issue, please reopen with any additional details or screenshots of the error / relevant code.
