### ISSUE TITLE
How to null a date

### ISSUE THREAD

**Issue by beppino** [bendavis78/paper-date-picker#30]
Hello,
sorry for this, maybe, obvious question, but I don't found a method to set null a date.
This is important because I've some non mandatory date fields in a form and the user must have some method to reset its value, if not null.
Also important to reset all date field after a "reset form" request.
I've tried to set date=null, date=undefined, date=''' but without success.
The same question also for your paper-time-picker element.
Can you help me?
Thanks
-g

**Comment by bendavis78** [comment]
It should already be possible to set a null date in `paper-date-picker`. What issue are you having? Can you provide an example that shows the problem in jsbin?

With regard to `paper-time-picker`, it cannot have a null value since the picker must always show a time. The pickers aren't meant to be form fields, so you might be wanting to use one-way binding, or perhaps use different intermediate properties for binding.

**Comment by beppino** [comment]
So @bendavis78 , I've to detach the pickers from the form, right?
The fields with date and time should be like input text to show the value and a button to open the pickers?
I'll try!
Ciao
