### ISSUE TITLE
Date picker shouldn't set the time

### ISSUE THREAD

**Issue by ronnyroeller** [bendavis78/paper-date-picker#50]
The `date-picker` defaults the time always to midnight:
https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L583

This makes using the data-picker in combination with the time-picker (https://github.com/bendavis78/paper-time-picker) more complicated:
Scenario:
1. User selects date (via date-picker)
2. User selects time (via time-picker)
3. User figures out that the date was incorrect -> user corrects the date

In this case, the user looses also the time selection.

**Comment by bendavis78** [comment]
Can you post an example of your use case?

**Comment by Zecat** [comment]
If I understand you set the hour for the time comparison to match as in 
```date.getTime() === this.today.getTime()```
Maybe we should use momentjs for that http://momentjs.com/docs/#/query/is-same/ because hours is not the point of interest of the calendar.

Also, setting today's date, then the hour in [_updateToday](https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L626) cause today attribute to change twice and [_getDayClass(item.date, today, date)](https://github.com/bendavis78/paper-date-picker/blob/master/paper-calendar.html#L174) is observing today so I suppose it will be called twice.

**Comment by ronnyroeller** [comment]
Ben, something along these lines (an element that combines the date and time picker to select a datetime):
```html
<html>
	<head>
	    <script src="../../webcomponentsjs/webcomponents-lite.js"></script>
		<link rel="import" href="../../paper-date-picker/paper-date-picker.html">
		<link rel="import" href="../../paper-time-picker/paper-time-picker.html">
	</head>

	<body>
		<template is="dom-bind">
			<h2>Date</h2>
			<paper-date-picker date={{date}}></paper-date-picker>

			<h2>Time</h2>
			<paper-time-picker id="time"></paper-time-picker>
			<button on-tap="saveTime">Save time</button>

			<h2>Selected datetime</h2>
			[[date]]
		</template>

		<script>
			var scope = document.querySelector("template[is=dom-bind]");
			scope.date = new Date();
			scope.saveTime = function(e) {
				var newDate = new Date(this.date.getTime());
				newDate.setHours(this.$.time.hour, this.$.time.minute);
				scope.date = newDate;
			};
		</script>
	</body>
</html>
```

**Comment by bendavis78** [comment]
Ah, I see. Yeah, it definitely shouldn't be modifying the time of a bound value. Marking this as bug for now.
