### ISSUE TITLE
CSS issues with MS Edge and Firefox browsers

### ISSUE THREAD

**Issue by vamsikrishna290** [bendavis78/paper-date-picker#73]
I am using this tools in one of the web apps. The tool seems great and working well in Chrome browser. But there are some css issue with MS edge and fire fox latest versions.
**MS edge:**

![image](https://cloud.githubusercontent.com/assets/10979402/12667749/ac351ed2-c675-11e5-96d8-5a78cc1a8067.png)

**Firefox:**

![image](https://cloud.githubusercontent.com/assets/10979402/12667771/ccb2ec52-c675-11e5-9da3-4c3eee1a755a.png)

Can you please resolve these issues.

**Comment by BootsSiR** [comment]
I've noticed this as well.  Love these components, would love to see this corrected.  I will try and take a look at it myself if I have enough time.

**Comment by BootsSiR** [comment]
Just something I found quickly on FF

![issue73](https://cloud.githubusercontent.com/assets/350484/12895908/67a37d56-ce75-11e5-88f1-17b710d13a88.gif)

**Comment by bendavis78** [comment]
Yikes. Thanks for the bug report. Feel free to submit a PR if you have time to look into it more. I might not have time to look into this for a little while. Marking as "help wanted" for now.

**Comment by mariocontext** [comment]
I fixed the FF issue using:

paper-date-picker::shadow paper-calendar .month-col {
        height: 30px;
      }

Might not be the ideal means to fix it but it works and doesn't seem to break Chrome, Safari and IE (edge)

Obviously, using shadow is not a good idea but it's what I had to work with instead of touching the core component.

I think the SVG circle throws things off in FF and expands the col to its dimensions if there is no explicit sizing apart from the calc values. I also noticed flex classes are being applied here and there instead of apply mixins. Maybe some classes are not being applied since I understand this approach is now deprecated.

Our QA person says it's now good in IE Edge as well. :)

FYI: Also ran into a sizing issue in Safari.

![ui_date picker_safari](https://cloud.githubusercontent.com/assets/2450595/13613033/302ac350-e51f-11e5-8624-49aed4efb48c.jpg)

It appears that it needed the -webkit-flex prefix here:

      paper-date-picker::shadow #pages.paper-date-picker {
        -webkit-flex: 1;
      }

@bendavis78 Thanks for creating this component. It's helped out team a lot!

**Comment by bendavis78** [comment]
@mariocontext, thanks for looking into this. Setting a fixed height on the day items is an ok workaround for others, but not a good fix for `paper-calendar` since the calendar's size can be changed. When the calendar's size changes, the date elements are spaced out evenly within the container, and the selection circle scales proportionally to fill the available width and height of that day cell. That's also the reason I'm using SVG -- I couldn't figure out a way to guarantee 1:1 proportions of an element using CSS, and using javascript for that seemed like overkill (though now I'm reconsidering it).
