### ISSUE TITLE
[Firefox] Month is skipped on arrow press

### ISSUE THREAD

**Issue by Link2Twenty** [bendavis78/paper-date-picker#91]
There are a few things that don't quite work write in firefox:

- Extra white bar below element
- Skips over month on arrow press*
- plays slide in animation on date select**

*
![ffbugskip](https://cloud.githubusercontent.com/assets/3534427/13748844/82fc4294-e9f6-11e5-99a7-28b85330189a.gif)

**
![ffbugslide](https://cloud.githubusercontent.com/assets/3534427/13748848/8b6f1ad2-e9f6-11e5-97d5-178aa3ee479f.gif)

**Comment by Mipme** [comment]
+1

**Comment by Mipme** [comment]
One issue is that the _transitionEvent is not detected correctly. But still jumping over multiple pages after some clicks...

**Comment by kyzrfranz** [comment]
Short interjection for a quick fix: I added a semaphore in _swipeNextMonth and _swipePrevMonth around the call to _translateX to avoid having to many events bound to the node - firefox seems to be having issues in adding and releasing them in order. It's still not 100% but a workaround for the time being - would suggest having a look at the _translateX Method - maybe it needs some way to abort a transition because that's what that flickering is coming from in the end.

**Comment by bendavis78** [comment]
Thanks for the fix, @rokkie!

**Comment by miguelcp646** [comment]
Hi, I'd like to know when will this fix be released.

Thanks.
